### ISSUE TITLE
De-activable Markdown conversion in CodeBlock

### ISSUE THREAD

**Issue by aureliensibiril** [jamalex/notion-py#31]
While using markdown_to_notion() for the ```title``` property makes lot's of sense for most blocks, it might be an issue for ```CodeBlock```.

I saw that property_map has a flag for markdown conversion but it's not accessible from the block initialisation. 

https://github.com/jamalex/notion-py/blob/ef0c5e02bd4ae5ad8d34c6c56e4e842b15aeaa01/notion/maps.py#L47

**Comment by Cobertos** [comment]
I'm having issues with this while trying to upload yaml documents of the format

```yaml
title: Test
tags:
  - Video Game Art
  - Blender
  - Modelling
  - Render
  - Cycles
  - Quackventures
permalink: test
id: 59f834a1fe4ed100192567da
updated: '2018-06-14T07:20:33.000Z'
date: 2016-02-08 03:59:20
```

cause issues. The yaml array gets parsed as Markdown and each line becomes separated by a new line and loses the array prefix `  - `
